### PR TITLE
OSOE-559: Make pnpm retries more robust to prevent errors - 2nd try

### PR DESCRIPTION
**Pull request by 0liver**
[OSOE-559](https://lombiq.atlassian.net/browse/OSOE-559)
This reverts commit 9b18545c0afeeb238c5d22ef087dd689bf7d428e.

[OSOE-559]: https://lombiq.atlassian.net/browse/OSOE-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by dministro** [comment]
If I understand well, the core issue is synchronization.

I would suggest a different approach instead of polling lock files in a loop because I feel scalability problems in the polling approach.
Will the number of retry enough if the number of projects is growing?

Here are some links for inspiration: 
https://stackoverflow.com/questions/62821122/msbuild-how-to-create-critical-section
https://gist.github.com/dedale/675ec80313f2a70266deb0ab78a0e2c6


Also you forget to mention powershell in docs.

**Review by dministro — CHANGES_REQUESTED** [review]
Please mention powershell in docs.

Also check my comment: https://github.com/Lombiq/NodeJs-Extensions/pull/36#issuecomment-1453421531

**Comment by 0liver** [comment]
I didn't mention PowerShell, because if it's not available, I will fallback to just retrying: https://github.com/Lombiq/NodeJs-Extensions/pull/36/files#diff-3a625bfa2aa0523fa32b46b74cdd39519196c3b9744bc3dc192ac2f9d6e3ae61R85.

**Comment by 0liver** [comment]
> If I understand well, the core issue is synchronization.

That's correct.

Thanks for both of the links you've added! I strayed from using a separate DLL for that task, but I guess it's not all that scary.

But even using a Mutex, we would still need to specify a timeout to avoid hanging, so there's always a non-zero probability that this might fail.

I think the current solution is good enough; which doesn't mean that it cannot be improved upon. But I would like to use this version to avoid at least most of the build errors that are currently popping up.

**Comment by dministro** [comment]
Ok then I added #37

**Comment by 0liver** [comment]
Closing in favor of https://github.com/Lombiq/NodeJs-Extensions/pull/38.

**Pull request closed without merging**
